### PR TITLE
Add qualityProfiles, tags, seasonSelection, delete command, configTextIdentifiers, admin option for sonarr/radarr, allowlist and minor fixes

### PR DESCRIPTION
**Pull request by anast20sm**
Changes:

- Changed messages flow. Once something is selected it is replaced with the new selection. (I found it chaotic how many messages were left after adding a single movie/series)
- Added delete command
- Added the capability to select quality profiles by name on Sonarr and Radarr (and possibility to exclude some of them)
- Added the capability to select which seasons to add on Sonarr
- Added the capability to define default tags and default language by name on config
- Changed config integer identifiers to string identifiers
- Added option to restrict series/movies list and delete to admin
- Allowlist option to define an allowlist by usernames/ids (more secure, but take in mind that is very restrictive)
- Other minor fixes

All modifications were done following the already written code format.

These changes should fix the following open issues:
https://github.com/Waterboy1602/Addarr/issues/16
https://github.com/Waterboy1602/Addarr/issues/35
https://github.com/Waterboy1602/Addarr/issues/49
https://github.com/Waterboy1602/Addarr/issues/75
https://github.com/Waterboy1602/Addarr/issues/85
https://github.com/Waterboy1602/Addarr/issues/87
https://github.com/Waterboy1602/Addarr/issues/92
https://github.com/Waterboy1602/Addarr/issues/105

### CODE REVIEW

**Comment by Waterboy1602** [comment]
Thank you a lot for all the new features! I'm testing the new code, but found a bug when trying to add a TV show that already exists. I get this error:
```
 File "[...]\addarr\addarr.py", line 640, in addSerieMovie
    selectedSeasons = [int(s) for s in context.user_data["seasons"] if int(s) >= int(try_fromSeason)]
KeyError: 'seasons'
```

I haven't yet found how to fix this bug, but I think it's best to first fix this bug before merging.

**Comment by anast20sm** [comment]
Of course, I will check it as soon as possible. Maybe I didn't take in mind some options (seems that I don't take "seasons" even though series already exist).
Will advice you once it is fixed!

**Comment by anast20sm** [comment]
Hi @Waterboy1602 , I'm not able to reproduce the bug. Could you please let me know which series were you adding? I tried with 1 season series, 1+specials series and 21 season series and they worked.

**Comment by Waterboy1602** [comment]
I've found the bug that created `KeyError: 'seasons'`. I've also found another bug that prevented to select `Execute a new search command` when you were at the step of `Is this a movie or a series?` and fixed it with my latest commit.

Now after some extra digging into all the commands, I've experienced some problems with the commands `/Movie` and `/Series`. They give the following error when executed:  
```
addarr\addarr.py", line 404, in searchSerieMovie
    message_id=context.user_data["update_msg"],
KeyError: 'update_msg'
```
When I find some extra time, I'll look into fixing this.

**Comment by anast20sm** [comment]
Fixed, it was a gap on the new flow. It used the messageId of choiceMovieSeries's message for future messages, but when using /series or /movie this message was skipped and then didn't find the messageId to edit. Thanks for advising!

**Comment by Waterboy1602** [comment]
I felt like the `/delete` commando needed an extra confirmation before effectively deleting the movie/series. So I've added this with my latest commit to this PR.

Now I feel like this PR is ready to be merged. Thank you for all your effort and work! I'll make a new tag (V0.6) when I've cleaned up the code and added some new features that I'm developing at the moment.

**Pull request merged**
